### PR TITLE
ci: add vro plugin build

### PR DESCRIPTION
**Pull request by little-dude**
cc @martin-leclerc

### CODE REVIEW

**Comment by little-dude** [comment]
build logs look good:

```
+generate-vspk -f . -L vro
[log] retrieving specifications from folder "."
[log] 187 specifications retrieved from folder "." (api version: 4.0)
[log] transforming specifications into vro for version 4.0...
[log] assembling...
[success] vspk generation complete and available in "./codegen/vro"
```

**Comment by little-dude** [comment]
now that it builds, let see if it gets pushed: https://travis-ci.org/nuagenetworks/vsd-api-specifications/builds/170243426

**Comment by martin-leclerc** [comment]
@little-dude It looks like the generated content ended up in the vro-plugin-base rep instead of the vspk-vro repo! 

Could you fix that please?

Martin.

**Comment by martin-leclerc** [comment]
@little-dude In your script, you need to replace vro-plugin-base with vspk-vro. That should do the trick.

Martin.

**Pull request merged**
