### PR TITLE
Updating the typo from DNS to DNA

### PR DESCRIPTION
**Pull request by mohaimenhasan**
DNA = Do not advertise
DNS = Domain Name System

### CODE REVIEW

**Comment by natabal** [comment]
@mohaimenhasan  This is not how we should update the SPECs cc @pdellaert The SPECs should be updated by the VSD team and then pushed here.

**Comment by pdellaert** [comment]
Hi @mohaimenhasan,

Thank you for your contribution! 

We don't accept PR's on this public repository as this is a mirror of our internal development repository which we sync for every release. The internal repository is the master.

However, I will take your changes, inspect them and if appropriate (which they are), include them in our development repository. Once that's done, I'll close this PR.

On our next release, your changes will then be included and synced into this repository.

Regards,
Philippe

**Comment by mohaimenhasan** [comment]
Hi @pdellaert. Just wanted to help out. Thanks

**Comment by pdellaert** [comment]
Which we really appreciate :), trust me! We make these specs open source with each release not only for people to use them in their automation if they want, but also to help in making them better if they see something like this.

So any contribution like yours is very welcome, it just has to follow an atypical process :)

**Comment by pdellaert** [comment]
@mohaimenhasan , thanks, i have ported this fix into our internal repository, which will be pushed to the public repository once the next release is released.

**Pull request closed without merging**
