### PR TITLE
Fixing supported NSG types in 4.0R10

### PR DESCRIPTION
**Pull request by pdellaert**
@little-dude, @natabal  Can you please check this.

I've confirmed that these are the proper NSG types supported in 4.0R10. This fix is urgently needed for a customer and we need to rerelease 4.0R10 VSPKs because of this fix.

### CODE REVIEW

**Review by little-dude — APPROVED** [review]
I didn't even know we had so many types of NSGs.
LGTM from a pure validity perspective. I can't tell if these values are correct though, but I trust you.

**Review by natabal — CHANGES_REQUESTED** [review]
This is a transient property can you please change transient to true as well?

**Comment by pdellaert** [comment]
@natabal , done :), including read-only as we discussed

**Review by natabal — APPROVED** [review]

**Comment by hellt** [comment]
Hi, Will this be propagated to 5.1.1+ releases?

**Comment by pdellaert** [comment]
This is already in the 5.1.1 release (at least the types, not the read-only/transient, but i can add those as well)

**Pull request merged**
