### PR TITLE
change "Alarm" -> "AllAlarm" entity name

### PR DESCRIPTION
**Pull request by little-dude**
@t00f please review. @martin-leclerc needs this for the java vspk.

### CODE REVIEW

**Comment by little-dude** [comment]
@martin-leclerc after discussion with @t00f this is mergeable. Can you test this and confirm that fixes the remaining issues with java vspk?

**Comment by t00f** [comment]
Waiting for @martin-leclerc for merging this PR.

**Comment by martin-leclerc** [comment]
I will take a look later today (5-6 hours)

Martin.

**Comment by martin-leclerc** [comment]
@t00f Change is good. vspk-java compiles fine with that change. You can merge this PR. Thank you.

**Comment by martin-leclerc** [comment]
@little-dude @t00f You can merge this PR - I don't think I have permissions to do it myself. Thank you.

**Pull request merged**
